[2015-12-13 01:29:18] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/orders/" (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/orders/\" at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/orders/\". at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2015-12-13 01:29:18] application.ERROR: No route found for "GET /api/v1/orders/" [] []
[2015-12-13 01:29:18] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:29:18] application.INFO: < 404 [] []
[2015-12-13 01:30:02] application.INFO: Matched route "GET_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:getAll","_route":"GET_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:30:02] application.INFO: > GET /api/v1/orders [] []
[2015-12-13 01:30:03] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT * FROM Order':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT * FROM Order':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2015-12-13 01:30:03] application.ERROR: An exception occurred while executing 'SELECT * FROM Order':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 [] []
[2015-12-13 01:30:03] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM O...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM O...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(9): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM O...') #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(20): api\Services\OrdersService->getAll() #5 [internal function]: api\Controllers\OrdersController->getAll() #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:30:03] application.INFO: < 500 [] []
[2015-12-13 01:30:03] application.INFO: Matched route "GET_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:getAll","_route":"GET_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:30:03] application.INFO: > GET /api/v1/orders [] []
[2015-12-13 01:30:03] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT * FROM Order':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT * FROM Order':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2015-12-13 01:30:03] application.ERROR: An exception occurred while executing 'SELECT * FROM Order':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order' at line 1 [] []
[2015-12-13 01:30:03] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM O...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM O...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(9): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM O...') #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(20): api\Services\OrdersService->getAll() #5 [internal function]: api\Controllers\OrdersController->getAll() #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:30:03] application.INFO: < 500 [] []
[2015-12-13 01:30:31] application.INFO: Matched route "GET_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:getAll","_route":"GET_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:30:31] application.INFO: > GET /api/v1/orders [] []
[2015-12-13 01:30:31] application.INFO: < 200 [] []
[2015-12-13 01:30:40] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/orders/" (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/orders/\" at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/orders/\". at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2015-12-13 01:30:40] application.ERROR: No route found for "GET /api/v1/orders/" [] []
[2015-12-13 01:30:40] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:30:40] application.INFO: < 404 [] []
[2015-12-13 01:30:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/orders/" (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/orders/\" at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/orders/\". at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2015-12-13 01:30:43] application.ERROR: No route found for "GET /api/v1/orders/" [] []
[2015-12-13 01:30:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:30:43] application.INFO: < 404 [] []
[2015-12-13 01:31:05] application.INFO: Matched route "GET_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:getAll","_route":"GET_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:31:05] application.INFO: > GET /api/v1/orders [] []
[2015-12-13 01:31:05] application.INFO: < 200 [] []
[2015-12-13 01:31:08] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/v1/orders/1\": Method Not Allowed (Allow: PUT, DELETE) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:127, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2015-12-13 01:31:08] application.ERROR: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) [] []
[2015-12-13 01:31:08] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:31:08] application.INFO: < 405 [] []
[2015-12-13 01:31:17] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/v1/orders/1\": Method Not Allowed (Allow: PUT, DELETE) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:127, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2015-12-13 01:31:17] application.ERROR: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) [] []
[2015-12-13 01:31:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:31:17] application.INFO: < 405 [] []
[2015-12-13 01:31:27] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/v1/orders/1\": Method Not Allowed (Allow: PUT, DELETE) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:127, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2015-12-13 01:31:27] application.ERROR: No route found for "GET /api/v1/orders/1": Method Not Allowed (Allow: PUT, DELETE) [] []
[2015-12-13 01:31:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(328): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(194): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:31:27] application.INFO: < 405 [] []
[2015-12-13 01:33:35] application.INFO: Matched route "GET_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:get","id":"1","_route":"GET_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:33:35] application.INFO: > GET /api/v1/orders/1 [] []
[2015-12-13 01:33:35] application.INFO: < 200 [] []
[2015-12-13 01:33:40] application.INFO: Matched route "GET_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:get","id":"2","_route":"GET_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/2"} []
[2015-12-13 01:33:40] application.INFO: > GET /api/v1/orders/2 [] []
[2015-12-13 01:33:41] application.INFO: < 200 [] []
[2015-12-13 01:33:47] application.INFO: Matched route "GET_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:get","id":"3","_route":"GET_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/3"} []
[2015-12-13 01:33:47] application.INFO: > GET /api/v1/orders/3 [] []
[2015-12-13 01:33:47] application.INFO: < 200 [] []
[2015-12-13 01:33:53] application.INFO: Matched route "GET_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:get","id":"1","_route":"GET_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:33:53] application.INFO: > GET /api/v1/orders/1 [] []
[2015-12-13 01:33:53] application.INFO: < 200 [] []
[2015-12-13 01:34:42] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:34:42] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:34:42] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, "1"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, \"1\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2015-12-13 01:34:42] application.ERROR: An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, "1"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 [] []
[2015-12-13 01:34:42] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE Order SE...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(669): Doctrine\DBAL\Connection->executeUpdate('UPDATE Order SE...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(25): Doctrine\DBAL\Connection->update('Order', Array, Array) #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(37): api\Services\OrdersService->update('1', Array) #5 [internal function]: api\Controllers\OrdersController->update('1', Object(Symfony\Component\HttpFoundation\Request)) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(242): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(259): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:34:42] application.INFO: < 500 [] []
[2015-12-13 01:37:18] application.INFO: Matched route "GET_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:get","id":"1","_route":"GET_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:37:18] application.INFO: > GET /api/v1/orders/1 [] []
[2015-12-13 01:37:18] application.INFO: < 200 [] []
[2015-12-13 01:37:42] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:37:42] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:37:42] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, "1"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, \"1\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2015-12-13 01:37:42] application.ERROR: An exception occurred while executing 'UPDATE Order SET order = ? WHERE id = ?' with params [null, "1"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order SET order = NULL WHERE id = '1'' at line 1 [] []
[2015-12-13 01:37:42] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE Order SE...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(669): Doctrine\DBAL\Connection->executeUpdate('UPDATE Order SE...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(25): Doctrine\DBAL\Connection->update('Order', Array, Array) #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(37): api\Services\OrdersService->update('1', Array) #5 [internal function]: api\Controllers\OrdersController->update('1', Object(Symfony\Component\HttpFoundation\Request)) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(242): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(259): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:37:42] application.INFO: < 500 [] []
[2015-12-13 01:38:49] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:38:49] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:38:49] application.INFO: < 200 [] []
[2015-12-13 01:39:33] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:39:33] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:39:33] application.INFO: < 200 [] []
[2015-12-13 01:41:29] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:41:29] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:41:29] application.INFO: < 200 [] []
[2015-12-13 01:41:42] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:41:42] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:41:42] application.INFO: < 200 [] []
[2015-12-13 01:41:55] application.INFO: Matched route "POST_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:save","_route":"POST_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:41:55] application.INFO: > POST /api/v1/orders [] []
[2015-12-13 01:41:55] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [null]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES (NULL)' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [null]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES (NULL)' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES (NULL)' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES (NULL)' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2015-12-13 01:41:55] application.ERROR: An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [null]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES (NULL)' at line 1 [] []
[2015-12-13 01:41:55] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO Ord...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO Ord...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(19): Doctrine\DBAL\Connection->insert('Order', Array) #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(31): api\Services\OrdersService->save(Array) #5 [internal function]: api\Controllers\OrdersController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(242): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(259): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:41:55] application.INFO: < 500 [] []
[2015-12-13 01:42:24] application.INFO: Matched route "POST_api_v1_orders". {"route_parameters":{"_controller":"orders.controller:save","_route":"POST_api_v1_orders"},"request_uri":"http://2hd.dev/api/v1/orders"} []
[2015-12-13 01:42:24] application.INFO: > POST /api/v1/orders [] []
[2015-12-13 01:42:24] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [10000]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES ('10000')' at line 1 (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [10000]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES ('10000')' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES ('10000')' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES ('10000')' at line 1 at /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2015-12-13 01:42:24] application.ERROR: An exception occurred while executing 'INSERT INTO Order (delivery_cost) VALUES (?)' with params [10000]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Order (delivery_cost) VALUES ('10000')' at line 1 [] []
[2015-12-13 01:42:24] application.ERROR: #0 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO Ord...', Array) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO Ord...', Array, Array) #3 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Services/OrdersService.php(19): Doctrine\DBAL\Connection->insert('Order', Array) #4 /home/vorobey/Workspace/github/hackathon/2hd/src/api/Controllers/OrdersController.php(31): api\Services\OrdersService->save(Array) #5 [internal function]: api\Controllers\OrdersController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(139): call_user_func_array(Array, Array) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(242): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(259): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #15 {main} [] []
[2015-12-13 01:42:24] application.INFO: < 500 [] []
[2015-12-13 01:42:33] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "PUT /api/v1/orders": Method Not Allowed (Allow: GET, POST) (uncaught exception) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"PUT /api/v1/orders\": Method Not Allowed (Allow: GET, POST) at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/EventListener/RouterListener.php:127, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2015-12-13 01:42:33] application.ERROR: No route found for "PUT /api/v1/orders": Method Not Allowed (Allow: GET, POST) [] []
[2015-12-13 01:42:33] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/Application.php(586): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(242): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(259): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /home/vorobey/Workspace/github/hackathon/2hd/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /home/vorobey/Workspace/github/hackathon/2hd/vendor/silex/silex/src/Silex/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /home/vorobey/Workspace/github/hackathon/2hd/web/index.php(13): Silex\HttpCache->run() #12 {main} [] []
[2015-12-13 01:42:33] application.INFO: < 405 [] []
[2015-12-13 01:42:40] application.INFO: Matched route "PUT_api_v1_orders_id". {"route_parameters":{"_controller":"orders.controller:update","id":"1","_route":"PUT_api_v1_orders_id"},"request_uri":"http://2hd.dev/api/v1/orders/1"} []
[2015-12-13 01:42:40] application.INFO: > PUT /api/v1/orders/1 [] []
[2015-12-13 01:42:40] application.INFO: < 200 [] []
